# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ patch-1]
  pull_request:
    branches: [ patch-1 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  psql:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
        # will assign a random free host port
        - 5432/tcp
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: psql --version 

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          apt-get update
          apt-get install --yes --no-install-recommends postgresql-clien
          psql -c 'CREATE DATABASE bit_schema_test;' -U postgres
          psql -c 'CREATE SCHEMA bitschema;' -U postgres -d bit_schema_test
          psql -c 'CREATE SCHEMA test_schema;' -U postgres -d bit_schema_test
          psql -c 'create SCHEMA test_schema_2;' -U postgres -d bit_schema_test
          psql -c '\dn;' -U postgres -d bit_schema_test
          psql -c 'show search_path;' -U postgres -d bit_schema_test
          psql -c "ALTER DATABASE bit_schema_test SET search_path TO bitschema,public;" -U postgres -d bit_schema_test
          psql -c 'show search_path;' -U postgres -d bit_schema_test
